blank_issues_enabled: true
contact_links:
  - name: Security policy
    url: https://github.com/Sheepdog-97/open-mmi/security/policy
    about: Please review the security policy before reporting security or safety issues.
