#!/usr/bin/env python3
"""Generate the human-readable status reference from the canonical registry."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from canbusd import status_registry as vehicle_statuses


DEFAULT_OUTPUT = Path("docs/vehicle-status-registry.md")


def _value_text(value: dict[str, object]) -> str:
    value_type = str(value["type"])
    parts = [value_type]
    if value.get("unit"):
        parts.append(str(value["unit"]))
    if "minimum" in value or "maximum" in value:
        minimum = value.get("minimum", "−∞")
        maximum = value.get("maximum", "∞")
        parts.append(f"{minimum}…{maximum}")
    if value_type == "enum":
        parts.append(", ".join(str(item) for item in value.get("values", [])))
    if value.get("nullable"):
        parts.append("nullable")
    return " · ".join(parts)


def render() -> str:
    registry = vehicle_statuses.registry_payload()
    lines = [
        "# Open MMI vehicle-status registry",
        "",
        "> Generated from `canbusd/data/vehicle-statuses.v1.json`. Do not edit this file by hand.",
        "",
        "Vehicle profiles translate manufacturer-specific CAN frames into these canonical persistent",
        "status paths. Paths describe human meaning; the registry separately records type, unit,",
        "nullability and lifecycle so downstream code does not need to understand a CAN address.",
        "",
        "> **The registry is a continuity checkpoint, not a walled garden.** Raw CAN discovery",
        "> remains open. Reuse an existing human meaning when it fits, or propose a genuinely new",
        "> universal status path in the same pull request as its first maintained vehicle mapping.",
        "",
        "See [`vehicle-contribution-workflow.md`](vehicle-contribution-workflow.md) for the open",
        "discovery, reuse and proposal workflow.",
        "",
        f"Registry: `{registry['registry_id']}` · schema version `{registry['schema_version']}`",
        "",
        "| Path | Category | Value contract | Lifecycle | Meaning |",
        "| --- | --- | --- | --- | --- |",
    ]
    for path, definition in registry["statuses"].items():
        description = definition["description"].replace("|", "\\|")
        lines.append(
            "| "
            f"`{path}` | {definition['category']} | "
            f"{_value_text(definition['value'])} | "
            f"{definition['status']} | {description} |"
        )
    lines.extend(
        [
            "",
            "## Where hex meets human form",
            "",
            "The Seat and Vauxhall CAN layouts may be completely different while the downstream",
            "status remains identical:",
            "",
            "```json",
            "{",
            '  "id": "0x470",',
            '  "byte": 1,',
            '  "type": "bitfield",',
            '  "path": "doors",',
            '  "fields": {',
            '    "front_right": "0x01"',
            "  }",
            "}",
            "```",
            "",
            "```json",
            "{",
            '  "id": "0x431",',
            '  "byte": 4,',
            '  "type": "bool",',
            '  "path": "doors.front_right",',
            '  "mask": "0x20",',
            '  "true": "0x20",',
            '  "false": "0x00"',
            "}",
            "```",
            "",
            "Both publish:",
            "",
            "```text",
            "doors.front_right = true",
            "```",
            "",
            "The CAN ID, byte, mask and encoding are vehicle-specific. The human meaning is shared.",
            "",
            "## Event or status?",
            "",
            "- Use an **event** for a momentary request such as `mute_toggle`.",
            "- Use a **status** for persistent state such as `doors.front_right` or",
            "  `parking.distance.rear_left`.",
            "- A discovery label such as `pdc_signal` is not rejected as research. Before it",
            "  becomes maintained, determine whether it is a button event, an active-state flag,",
            "  or a measured parking distance, then reuse or propose the matching canonical concept.",
            "",
            "## Lifecycle",
            "",
            "- `stable` — supported human-facing contract.",
            "- `experimental` — useful interpretation that still needs confirmation.",
            "- `diagnostic` — raw or reverse-engineering output; not a stable UI contract.",
            "- `deprecated` — retained only for migration.",
            "",
            "## Tooling",
            "",
            "```bash",
            "open-mmi-config vehicle-setup statuses",
            "open-mmi-config vehicle-setup statuses --search \"right door\"",
            "open-mmi-config vehicle-setup statuses --search pdc_signal",
            "open-mmi-config vehicle-setup statuses --check doors.front_right",
            "open-mmi-config vehicle-setup statuses --check pdc_signal",
            "open-mmi-config vehicle-setup statuses parking.distance.rear_left",
            "```",
            "",
            "Verify this generated document:",
            "",
            "```bash",
            "python tools/generate_vehicle_status_docs.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated documentation: {args.output}", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                f"generated documentation is stale: {args.output}",
                file=sys.stderr,
            )
            return 1
        print(f"Verified generated vehicle-status documentation: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
