#!/usr/bin/env python3
"""Generate maintained vehicle catalogue and capability documentation."""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable, Mapping

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ui import vehicle_profile_conformance


DEFAULT_CATALOGUE_OUTPUT = Path("docs/vehicle-catalogue.md")
DEFAULT_MATRIX_OUTPUT = Path("docs/vehicle-capability-matrix.md")


def _markdown(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _code_list(values: Iterable[object]) -> str:
    items = [f"`{_markdown(value)}`" for value in values]
    return ", ".join(items) if items else "—"


def _text_list(values: Iterable[object]) -> str:
    items = [_markdown(value) for value in values]
    return ", ".join(items) if items else "—"


def _profile_key(profile: Mapping[str, Any]) -> tuple[str, str, str, str, str]:
    metadata = profile.get("metadata", {})
    return (
        str(metadata.get("manufacturer", "")),
        str(metadata.get("model", "")),
        str(metadata.get("generation", "")),
        str(metadata.get("platform", "")),
        str(profile.get("id", "")),
    )


def _valid_profiles(report: Mapping[str, Any]) -> list[dict[str, Any]]:
    if not report.get("valid"):
        problems: list[str] = []
        for profile in report.get("profiles", []):
            if profile.get("valid"):
                continue
            errors = profile.get("validation", {}).get("errors", [])
            detail = "; ".join(str(item.get("message", "invalid")) for item in errors)
            problems.append(f"{profile.get('id', 'unknown')}: {detail or 'invalid'}")
        raise ValueError("maintained vehicle catalogue is invalid: " + " | ".join(problems))
    profiles = [
        dict(profile)
        for profile in report.get("profiles", [])
        if profile.get("id") != "_catalogue"
    ]
    return sorted(profiles, key=_profile_key)


def _year_range(metadata: Mapping[str, Any]) -> str:
    years = metadata.get("model_years", {})
    return f"{years.get('from', '—')}–{years.get('to', '—')}"


def _qualification(profile: Mapping[str, Any]) -> Mapping[str, Any]:
    metadata = profile.get("metadata", {})
    qualification = metadata.get("qualification", {})
    return qualification if isinstance(qualification, Mapping) else {}


def _market_aliases(profile: Mapping[str, Any]) -> list[str]:
    metadata = profile.get("metadata", {})
    values = metadata.get("market_aliases", [])
    return [str(value) for value in values] if isinstance(values, list) else []


def _evidence_summary(profile: Mapping[str, Any]) -> str:
    evidence = _qualification(profile).get("evidence", [])
    counts = Counter(
        str(item.get("kind", "unknown"))
        for item in evidence
        if isinstance(item, Mapping)
    )
    if not counts:
        return "—"
    return ", ".join(f"{kind}: {counts[kind]}" for kind in sorted(counts))


def render_catalogue(report: Mapping[str, Any]) -> str:
    profiles = _valid_profiles(report)
    navigation: dict[str, dict[str, list[dict[str, Any]]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for profile in profiles:
        metadata = profile["metadata"]
        navigation[str(metadata["manufacturer"])][str(metadata["model"])].append(profile)

    lines = [
        "# Open MMI maintained vehicle catalogue",
        "",
        "> Generated from `vehicles/catalogue.v1.json` and maintained profile metadata. Do not edit this file by hand.",
        "",
        "This catalogue shows where each maintained vehicle integration lives, the stable profile identity",
        "used by runtime callers, what has been qualified, and which canonical capabilities are covered.",
        "A listed profile is a bounded compatibility claim, not a restriction on new vehicle research.",
        "",
        "## Navigation",
        "",
    ]
    for manufacturer in sorted(navigation):
        lines.append(f"- **{_markdown(manufacturer)}**")
        for model in sorted(navigation[manufacturer]):
            lines.append(f"  - **{_markdown(model)}**")
            for profile in sorted(navigation[manufacturer][model], key=_profile_key):
                metadata = profile["metadata"]
                label = f"{metadata['generation']} — {metadata['platform']}"
                lines.append(
                    f"    - [{_markdown(label)}](#{profile['id']}) (`{profile['id']}`)"
                )

    lines.extend(
        [
            "",
            "## Catalogue summary",
            "",
            "| Profile | Vehicle | Years | Maturity | Qualification | Last tested | Legacy aliases | Compatible market names | Replay coverage | Evidence | Canonical capabilities |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for profile in profiles:
        metadata = profile["metadata"]
        qualification = _qualification(profile)
        fixtures = profile.get("fixtures", {})
        coverage = fixtures.get("coverage", {})
        replay = (
            f"{fixtures.get('case_count', 0)} cases; "
            f"{coverage.get('events', 0)}/{coverage.get('event_total', 0)} events; "
            f"{coverage.get('statuses', 0)}/{coverage.get('status_total', 0)} statuses"
        )
        capabilities = profile.get("capabilities", {})
        lines.append(
            "| "
            f"[`{profile['id']}`](#{profile['id']}) | "
            f"{_markdown(metadata['display_name'])} | {_year_range(metadata)} | "
            f"{_markdown(metadata['maturity'])} | {_markdown(qualification.get('level', '—'))} | "
            f"{_markdown(qualification.get('last_tested') or '—')} | "
            f"{_code_list(profile.get('aliases', []))} | {_text_list(_market_aliases(profile))} | "
            f"{_markdown(replay)} | {_markdown(_evidence_summary(profile))} | "
            f"{capabilities.get('event_count', 0)} events; {capabilities.get('status_count', 0)} statuses |"
        )

    lines.extend(["", "## Profiles", ""])
    for profile in profiles:
        metadata = profile["metadata"]
        qualification = _qualification(profile)
        capabilities = profile.get("capabilities", {})
        fixtures = profile.get("fixtures", {})
        coverage = fixtures.get("coverage", {})
        lines.extend(
            [
                f'<a id="{profile["id"]}"></a>',
                f"### {_markdown(metadata['display_name'])}",
                "",
                f"- Stable ID: `{profile['id']}`",
                f"- Maintained path: `{profile['path']}`",
                f"- Manufacturer / model: {_markdown(metadata['manufacturer'])} {_markdown(metadata['model'])}",
                f"- Generation / platform: {_markdown(metadata['generation'])} / {_markdown(metadata['platform'])}",
                f"- Model years: {_year_range(metadata)}",
                f"- Maturity: `{metadata['maturity']}`",
                f"- Qualification: `{qualification.get('level', 'none')}`; last tested `{qualification.get('last_tested') or 'not recorded'}`",
                f"- Legacy aliases: {_code_list(profile.get('aliases', []))}",
                f"- Compatible market names: {_text_list(_market_aliases(profile))}",
                f"- CAN buses: {_code_list(capabilities.get('buses', []))}",
                f"- Replay proof: `{fixtures.get('path', 'not present')}`; {fixtures.get('case_count', 0)} cases; "
                f"{coverage.get('events', 0)}/{coverage.get('event_total', 0)} events and "
                f"{coverage.get('statuses', 0)}/{coverage.get('status_total', 0)} statuses covered",
                "",
                "#### Qualification scope",
                "",
            ]
        )
        scope = qualification.get("scope", [])
        lines.extend(f"- {_markdown(item)}" for item in scope)
        if not scope:
            lines.append("- No qualification scope declared.")

        lines.extend(["", "#### Evidence", ""])
        evidence = qualification.get("evidence", [])
        for item in evidence:
            lines.append(
                f"- `{item['kind']}` — [`{_markdown(item['path'])}`](../{item['path']}): "
                f"{_markdown(item['description'])}"
            )
        if not evidence:
            lines.append("- No evidence declared.")

        lines.extend(["", "#### Limitations", ""])
        limitations = metadata.get("limitations", [])
        lines.extend(f"- {_markdown(item)}" for item in limitations)
        if not limitations:
            lines.append("- No limitations declared.")

        lines.extend(
            [
                "",
                "#### Canonical events",
                "",
                _code_list(capabilities.get("events", [])),
                "",
                "#### Canonical statuses",
                "",
                _code_list(capabilities.get("statuses", [])),
                "",
            ]
        )

    lines.extend(
        [
            "## Regeneration",
            "",
            "```bash",
            "python tools/generate_vehicle_catalogue_docs.py",
            "python tools/generate_vehicle_catalogue_docs.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _matrix_table(
    profiles: list[dict[str, Any]],
    *,
    capability_key: str,
    label: str,
) -> list[str]:
    profile_ids = [str(profile["id"]) for profile in profiles]
    capabilities = sorted(
        {
            str(capability)
            for profile in profiles
            for capability in profile.get("capabilities", {}).get(capability_key, [])
        }
    )
    lines = [
        f"## {label}",
        "",
        "| Canonical descriptor | " + " | ".join(f"`{identifier}`" for identifier in profile_ids) + " |",
        "| --- | " + " | ".join("---" for _ in profile_ids) + " |",
    ]
    for capability in capabilities:
        cells = []
        for profile in profiles:
            supported = capability in profile.get("capabilities", {}).get(capability_key, [])
            cells.append("Yes" if supported else "—")
        lines.append(f"| `{_markdown(capability)}` | " + " | ".join(cells) + " |")
    if not capabilities:
        lines.append("| — | " + " | ".join("—" for _ in profile_ids) + " |")
    lines.append("")
    return lines


def render_capability_matrix(report: Mapping[str, Any]) -> str:
    profiles = _valid_profiles(report)
    lines = [
        "# Open MMI vehicle capability matrix",
        "",
        "> Generated from maintained vehicle profiles. Do not edit this file by hand.",
        "",
        "The matrix compares canonical event and status coverage across maintained integrations.",
        "A blank cell means the maintained profile does not currently claim that capability; it does",
        "not prove that the physical vehicle lacks the feature.",
        "",
        "## Profile key",
        "",
        "| Profile | Vehicle | Maturity | Qualification | Last tested | Events | Statuses |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for profile in profiles:
        metadata = profile["metadata"]
        qualification = _qualification(profile)
        capabilities = profile.get("capabilities", {})
        lines.append(
            f"| `{profile['id']}` | {_markdown(metadata['display_name'])} | "
            f"{_markdown(metadata['maturity'])} | {_markdown(qualification.get('level', '—'))} | "
            f"{_markdown(qualification.get('last_tested') or '—')} | "
            f"{capabilities.get('event_count', 0)} | {capabilities.get('status_count', 0)} |"
        )
    lines.append("")
    lines.extend(_matrix_table(profiles, capability_key="events", label="Canonical events"))
    lines.extend(_matrix_table(profiles, capability_key="statuses", label="Canonical statuses"))
    lines.extend(
        [
            "## Regeneration",
            "",
            "```bash",
            "python tools/generate_vehicle_catalogue_docs.py",
            "python tools/generate_vehicle_catalogue_docs.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def render_documents(root: Path) -> tuple[str, str]:
    report = vehicle_profile_conformance.catalogue_report(root)
    return render_catalogue(report), render_capability_matrix(report)


def _write_or_check(path: Path, content: str, *, check: bool, label: str) -> bool:
    if check:
        try:
            current = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated documentation: {path}", file=sys.stderr)
            return False
        if current != content:
            print(f"generated documentation is stale: {path}", file=sys.stderr)
            return False
        print(f"Verified generated {label}: {path}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"Generated {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--catalogue-output", type=Path, default=DEFAULT_CATALOGUE_OUTPUT)
    parser.add_argument("--matrix-output", type=Path, default=DEFAULT_MATRIX_OUTPUT)
    args = parser.parse_args()
    root = args.root.expanduser().resolve()
    try:
        catalogue, matrix = render_documents(root)
    except (OSError, ValueError, vehicle_profile_conformance.VehicleProfileConformanceError) as exc:
        print(f"cannot generate vehicle catalogue documentation: {exc}", file=sys.stderr)
        return 1
    ok_catalogue = _write_or_check(
        args.catalogue_output, catalogue, check=args.check, label="vehicle catalogue documentation"
    )
    ok_matrix = _write_or_check(
        args.matrix_output, matrix, check=args.check, label="vehicle capability matrix"
    )
    return 0 if ok_catalogue and ok_matrix else 1


if __name__ == "__main__":
    raise SystemExit(main())
