#!/usr/bin/env python3
"""Generate the human-readable event reference from the canonical registry."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from canbusd import event_registry as vehicle_events


DEFAULT_OUTPUT = Path("docs/vehicle-event-registry.md")


def _payload_text(payload: dict[str, object]) -> str:
    if payload["type"] == "none":
        return "None"
    return (
        f"Integer {payload['minimum']}–{payload['maximum']} "
        f"{payload['unit']}"
    )


def render() -> str:
    registry = vehicle_events.registry_payload()
    lines = [
        "# Open MMI vehicle-event registry",
        "",
        "> Generated from `canbusd/data/vehicle-events.v1.json`. Do not edit this file by hand.",
        "",
        "Vehicle profiles translate manufacturer-specific CAN signals into these canonical events.",
        "Bindings map the same events to application actions. Event names describe universal intent",
        "or state transitions; they never describe a vehicle model, CAN address, Python module or function.",
        "",
        "> **The registry is a continuity checkpoint, not a walled garden.** Raw CAN discovery",
        "> remains open. Reuse an existing human meaning when it fits, or propose a genuinely new",
        "> universal event in the same pull request as its first maintained vehicle mapping.",
        "",
        "See [`vehicle-contribution-workflow.md`](vehicle-contribution-workflow.md) for the open",
        "discovery, reuse and proposal workflow.",
        "",
        f"Registry: `{registry['registry_id']}` · schema version `{registry['schema_version']}`",
        "",
        "| Event | Category | Payload | Delivery | Status | Meaning |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for event, definition in registry["events"].items():
        description = definition["description"].replace("|", "\\|")
        lines.append(
            "| "
            f"`{event}` | {definition['category']} | "
            f"{_payload_text(definition['payload'])} | "
            f"{definition['delivery']} | {definition['status']} | "
            f"{description} |"
        )
    lines.extend(
        [
            "",
            "## Canonical mapping example",
            "",
            "Different vehicles may encode the same user intent differently. The event identifier stays the same:",
            "",
            "```json",
            "{",
            '  "id": "0x5C1",',
            '  "byte": 0,',
            '  "value": 43,',
            '  "event": "mute_toggle"',
            "}",
            "```",
            "",
            "```json",
            "{",
            '  "id": "0x231",',
            '  "byte": 3,',
            '  "value": 30,',
            '  "event": "mute_toggle"',
            "}",
            "```",
            "",
            "The binding is independent of both CAN layouts:",
            "",
            "```json",
            "{",
            '  "mute_toggle": {',
            '    "module": "audio",',
            '    "func": "mute_toggle"',
            "  }",
            "}",
            "```",
            "",
            "## Registry rules",
            "",
            "- Existing canonical names are immutable. Their meaning cannot be silently changed.",
            "- Raw discovery notes may use provisional names; the canonical requirement begins at the maintained-profile boundary.",
            "- New universal concepts may be added to the registry in the same pull request as their first maintained mapping.",
            "- Manufacturer, model, CAN ID, module and function names do not belong in canonical event names.",
            "- Deprecated aliases are migration diagnostics only; profiles and bindings must use the canonical name.",
            "- A rule using `value: \"any\"` forwards a value and therefore requires an event with a payload contract.",
            "- Presence transitions cannot emit events that require a payload.",
            "",
            "## Tooling",
            "",
            "Print the complete registry:",
            "",
            "```bash",
            "open-mmi-config vehicle-setup events",
            "```",
            "",
            "Search using ordinary human wording:",
            "",
            "```bash",
            "open-mmi-config vehicle-setup events --search mute",
            "open-mmi-config vehicle-setup events --search \"audio volume\"",
            "```",
            "",
            "Check whether to reuse or propose an identifier:",
            "",
            "```bash",
            "open-mmi-config vehicle-setup events --check mute_toggle",
            "open-mmi-config vehicle-setup events --check pdc_signal",
            "```",
            "",
            "Inspect one exact event:",
            "",
            "```bash",
            "open-mmi-config vehicle-setup events mute_toggle",
            "```",
            "",
            "Verify this generated document:",
            "",
            "```bash",
            "python tools/generate_vehicle_event_docs.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated documentation: {args.output}", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                f"generated documentation is stale: {args.output}",
                file=sys.stderr,
            )
            return 1
        print(f"Verified generated vehicle-event documentation: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
