#!/usr/bin/env python3
"""Generate the human-readable action reference from the canonical registry."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from canbusd import action_registry as vehicle_actions


DEFAULT_OUTPUT = Path("docs/vehicle-action-registry.md")


def _contract_text(contract: dict[str, object]) -> str:
    if contract["type"] == "none":
        return "None"
    text = str(contract["type"])
    if "minimum" in contract and "maximum" in contract:
        text += f" {contract['minimum']}–{contract['maximum']}"
    if contract.get("unit"):
        text += f" {contract['unit']}"
    return text


def _arguments_text(arguments: list[dict[str, object]]) -> str:
    if not arguments:
        return "None"
    rendered = []
    for argument in arguments:
        required = "required" if argument["required"] else "optional"
        default = (
            f", default `{argument['default']}`"
            if "default" in argument
            else ""
        )
        rendered.append(
            f"`{argument['name']}` ({argument['type']}, {required}{default})"
        )
    return "; ".join(rendered)


def render() -> str:
    registry = vehicle_actions.registry_payload()
    lines = [
        "# Open MMI vehicle-action registry",
        "",
        "> Generated from `canbusd/data/vehicle-actions.v1.json`. Do not edit this file by hand.",
        "",
        "Bindings translate canonical vehicle events into these stable local behaviors. The action",
        "identifier describes what Open MMI should do; Python modules, function names, commands and",
        "packages remain private implementation details owned by the registry.",
        "",
        "> **The action registry is a continuity checkpoint, not a walled garden.** Reuse an",
        "> existing human-readable behavior when it fits, or propose a genuinely new action,",
        "> implementation, documentation and tests in the same pull request.",
        "",
        f"Registry: `{registry['registry_id']}` · schema version `{registry['schema_version']}`",
        "",
        "| Action | Category | Configured arguments | Event payload | Requirements | Status | Meaning |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for action, definition in registry["actions"].items():
        description = definition["description"].replace("|", "\\|")
        requirements = ", ".join(f"`{item}`" for item in definition["requirements"]) or "None"
        lines.append(
            "| "
            f"`{action}` | {definition['category']} | "
            f"{_arguments_text(definition['arguments'])} | "
            f"{_contract_text(definition['event_payload'])} | "
            f"{requirements} | {definition['status']} | {description} |"
        )
    lines.extend(
        [
            "",
            "## Binding example",
            "",
            "A maintained binding names a stable action, not its Python implementation:",
            "",
            "```json",
            "{",
            '  "mute_toggle": {',
            '    "action": "media.mute.toggle"',
            "  },",
            '  "brightness_level": {',
            '    "action": "display.brightness.set"',
            "  }",
            "}",
            "```",
            "",
            "The event says what happened. The action says what Open MMI should do. The registry",
            "privately resolves the action to the current implementation.",
            "",
            "## Compatibility boundary",
            "",
            "Existing custom bindings using `module`, `func` and `args` remain supported during the",
            "migration window and receive a validation warning. Maintained bindings must use canonical",
            "action identifiers. New contributions must not expose Python implementation names in the",
            "maintained binding catalogue.",
            "",
            "## Reuse or propose",
            "",
            "Search using ordinary language before adding a new action:",
            "",
            "```bash",
            "open-mmi-config vehicle-setup actions --search \"audio mute\"",
            "open-mmi-config vehicle-setup actions --search \"screen power off\"",
            "```",
            "",
            "Check an exact proposed identifier:",
            "",
            "```bash",
            "open-mmi-config vehicle-setup actions --check media.mute.toggle",
            "open-mmi-config vehicle-setup actions --check sound_module_off",
            "```",
            "",
            "A new action proposal should define the universal behavior, argument contract, event-payload",
            "contract, requirements, implementation and tests. No prior permission is required; registry",
            "review prevents duplicate dialects and implementation details from becoming public API.",
            "",
            "## Registry rules",
            "",
            "- Existing stable action identifiers never silently change meaning.",
            "- Action names describe local behavior, not the event that triggered it.",
            "- Manufacturer names, CAN IDs, Python modules, functions and executable names do not belong in action IDs.",
            "- Configured arguments and event payloads are separate, validated contracts.",
            "- Deprecated aliases are migration diagnostics only; maintained bindings use the canonical identifier.",
            "- Availability requirements are descriptive and may be surfaced by future capability tooling.",
            "",
            "## Verify this document",
            "",
            "```bash",
            "python tools/generate_vehicle_action_docs.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated documentation: {args.output}", file=sys.stderr)
            return 1
        if current != rendered:
            print(f"generated documentation is stale: {args.output}", file=sys.stderr)
            return 1
        print(f"Verified generated vehicle-action documentation: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
