"""Concrete, fixed-path vehicle configuration apply operations.

This module contains the root-owned filesystem and service operations used by
``vehicle_config_coordinator.run_apply_transaction``. Keeping these operations
in a separate module preserves a narrow privileged surface for rendering,
snapshot, atomic replacement, verification and restoration while the fixed
socket/HTTP action supplies only a reviewed normalized target.
"""

from __future__ import annotations

import hashlib
import json
import os
import pwd
import re
import shutil
import stat
import subprocess
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, Mapping, Optional, Sequence

from ui import vehicle_configuration, vehicle_setup


SNAPSHOT_SCHEMA_VERSION = 1
DEFAULT_DESCRIPTOR_PATH = Path("/etc/open-mmi/vehicle-configuration.json")
DEFAULT_UDEV_RULE_PATH = Path("/etc/udev/rules.d/80-canbus.rules")
DEFAULT_ROLLBACK_ROOT = Path("/var/lib/open-mmi/vehicle-configuration-rollback")
MAX_ARTIFACT_BYTES = 256 * 1024
DEFAULT_COMMAND_TIMEOUT = 20.0
DEFAULT_LOADED_TIMEOUT = 12.0
DEFAULT_POLL_INTERVAL = 0.1
_TRANSACTION_RE = re.compile(r"^configuration-[0-9a-f]{32}$")
_SAFE_USER_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")


def _unique_json_object(pairs: Sequence[tuple[str, Any]]) -> Dict[str, Any]:
    result: Dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ApplyOperationError("Duplicate JSON field")
        result[key] = value
    return result


def _reject_json_constant(value: str) -> None:
    raise ApplyOperationError("Invalid JSON number")


class ApplyOperationError(RuntimeError):
    """A fixed-operation failure safe to collapse at the public boundary."""


@dataclass(frozen=True)
class RenderedArtifacts:
    descriptor: bytes
    runtime_dropin: bytes
    udev_rules: bytes


@dataclass(frozen=True)
class FileSnapshot:
    present: bool
    content: bytes
    mode: int
    uid: int
    gid: int


@dataclass(frozen=True)
class ApplySnapshot:
    transaction_id: str
    directory: Path
    files: Mapping[str, FileSnapshot]
    previous_loaded: Mapping[str, Any]


@dataclass(frozen=True)
class ApplyPaths:
    descriptor: Path
    runtime_dropin: Path
    udev_rules: Path
    runtime_status: Path
    rollback_root: Path


CommandRunner = Callable[[Sequence[str], bool], None]


def _timestamp() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _json_bytes(payload: Mapping[str, Any]) -> bytes:
    return (json.dumps(dict(payload), indent=2, sort_keys=True) + "\n").encode("utf-8")


def _comment_value(value: object) -> str:
    text = str(value)
    if any(ord(character) < 32 for character in text):
        raise ApplyOperationError("Generated configuration comment is invalid")
    return text


def _systemd_quote(value: str) -> str:
    if not isinstance(value, str) or any(ord(character) < 32 for character in value):
        raise ApplyOperationError("Runtime environment value is invalid")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _runtime_dropin_text(
    target: Mapping[str, Any], profile_path: Path, bindings_path: Path
) -> str:
    active_bus = target["runtime"]["active_bus"]
    interface = target["runtime"]["buses"][active_bus]["interface"]
    values = {
        "OPEN_MMI_VEHICLE": target["vehicle"]["id"],
        "OPEN_MMI_BINDINGS": target["bindings"]["id"],
        "OPEN_MMI_VEHICLE_CONFIG": str(profile_path),
        "OPEN_MMI_BINDINGS_FILE": str(bindings_path),
        "OPEN_MMI_CAN_BUS": active_bus,
        "OPEN_MMI_CAN_INTERFACE": interface,
    }
    lines = [
        "# Generated by the Open MMI vehicle configuration coordinator.",
        "# Do not edit this file while a configuration transaction is active.",
        "",
        "[Service]",
    ]
    lines.extend(
        f"Environment={_systemd_quote(f'{key}={value}')}"
        for key, value in values.items()
    )
    return "\n".join(lines) + "\n"


def _udev_rules_text(
    target: Mapping[str, Any],
    profile_path: Path,
    bus: Mapping[str, Any],
    *,
    suppress_can_provisioning: bool = False,
) -> str:
    active_bus = target["runtime"]["active_bus"]
    interface = target["runtime"]["buses"][active_bus]["interface"]
    lines = [
        "# Generated by the Open MMI vehicle configuration coordinator.",
        f"# Vehicle profile: {target['vehicle']['id']}",
        f"# Source profile: {_comment_value(profile_path)}",
        f"# Active CAN bus: {active_bus}",
        "# canbusd remains a passive SocketCAN consumer.",
        "",
    ]
    provisioning = bus.get("provisioning")
    bitrate = bus.get("bitrate")
    if suppress_can_provisioning:
        lines.extend(
            [
                f"# CAN bus {active_bus}: vcan qualification; no hardware rule generated.",
                "",
            ]
        )
    elif provisioning == "udev" and isinstance(bitrate, int) and bitrate > 0:
        lines.extend(
            [
                f"# CAN bus {active_bus}",
                f'SUBSYSTEM=="net", KERNEL=="{interface}", ACTION=="add", '
                f'RUN+="/sbin/ip link set {interface} down", '
                f'RUN+="/sbin/ip link set {interface} type can bitrate {bitrate}", '
                f'RUN+="/sbin/ip link set {interface} up"',
                "",
            ]
        )
    else:
        lines.extend(
            [
                f"# CAN bus {active_bus}: provisioning={provisioning}; no CAN rule generated.",
                "",
            ]
        )
    lines.extend(
        [
            "# Local UI/input support used by Open MMI actions.",
            'KERNEL=="uinput", MODE="0666"',
            'SUBSYSTEM=="backlight", KERNEL=="intel_backlight", GROUP="video", MODE="0664"',
            "",
        ]
    )
    return "\n".join(lines)


def _read_catalogue_document(
    path: Path,
    maximum_bytes: int,
    *,
    expected_uid: Optional[int],
) -> tuple[Mapping[str, Any], str]:
    item = _read_file(path, maximum_bytes)
    if not item.present:
        raise ApplyOperationError("Catalogue document is missing")
    if len(item.content) > maximum_bytes:
        raise ApplyOperationError("Catalogue document exceeds the size limit")
    if item.mode & 0o7133:
        raise ApplyOperationError("Catalogue document permissions are unsafe")
    if expected_uid is not None and item.uid != expected_uid:
        raise ApplyOperationError("Catalogue document owner is untrusted")
    try:
        document = json.loads(
            item.content.decode("utf-8"),
            object_pairs_hook=_unique_json_object,
            parse_constant=_reject_json_constant,
        )
    except (UnicodeDecodeError, json.JSONDecodeError, ApplyOperationError) as exc:
        raise ApplyOperationError("Catalogue document is not valid UTF-8 JSON") from exc
    if not isinstance(document, Mapping):
        raise ApplyOperationError("Catalogue document must contain an object")
    return document, "sha256:" + hashlib.sha256(item.content).hexdigest()


def render_artifacts(
    target: Mapping[str, Any],
    roots: vehicle_setup.CatalogueRoots,
    *,
    applied_at: Optional[str] = None,
    maintained_uid: Optional[int] = None,
    custom_uid: Optional[int] = None,
    suppress_can_provisioning: bool = False,
) -> RenderedArtifacts:
    """Resolve, revalidate and render all generated configuration bytes."""

    try:
        normalized = vehicle_configuration.normalize_selection(target)
        profile_path = vehicle_setup.resolve_catalogue_path(
            roots,
            "profile",
            normalized["vehicle"]["source"],
            normalized["vehicle"]["id"],
        )
        bindings_path = vehicle_setup.resolve_catalogue_path(
            roots,
            "bindings",
            normalized["bindings"]["source"],
            normalized["bindings"]["id"],
        )
        profile_expected_uid = (
            maintained_uid
            if normalized["vehicle"]["source"] == "maintained"
            else custom_uid
        )
        bindings_expected_uid = (
            maintained_uid
            if normalized["bindings"]["source"] == "maintained"
            else custom_uid
        )
        profile, profile_revision = _read_catalogue_document(
            profile_path,
            vehicle_setup.MAX_PROFILE_BYTES,
            expected_uid=profile_expected_uid,
        )
        bindings, bindings_revision = _read_catalogue_document(
            bindings_path,
            vehicle_setup.MAX_BINDINGS_BYTES,
            expected_uid=bindings_expected_uid,
        )
        profile_validation = vehicle_setup.validate_profile(profile)
        bindings_validation = vehicle_setup.validate_bindings(bindings)
        if not profile_validation["valid"]:
            raise ApplyOperationError("Selected vehicle profile is invalid")
        if not bindings_validation["valid"]:
            raise ApplyOperationError("Selected bindings are invalid")
        if profile_revision != normalized["vehicle"]["revision"]:
            raise ApplyOperationError("Vehicle profile changed before installation")
        if bindings_revision != normalized["bindings"]["revision"]:
            raise ApplyOperationError("Bindings changed before installation")
        bus = vehicle_setup._profile_bus_metadata(  # type: ignore[attr-defined]
            profile, normalized["runtime"]["active_bus"]
        )
        descriptor = vehicle_configuration.descriptor_for_selection(
            normalized, applied_at=applied_at or _timestamp()
        )
    except ApplyOperationError:
        raise
    except (
        vehicle_configuration.VehicleConfigurationError,
        vehicle_setup.VehicleSetupError,
        KeyError,
        TypeError,
    ) as exc:
        raise ApplyOperationError("Vehicle configuration artifacts cannot be rendered") from exc

    return RenderedArtifacts(
        descriptor=_json_bytes(descriptor),
        runtime_dropin=_runtime_dropin_text(normalized, profile_path, bindings_path).encode(
            "utf-8"
        ),
        udev_rules=_udev_rules_text(
            normalized,
            profile_path,
            bus,
            suppress_can_provisioning=suppress_can_provisioning,
        ).encode("utf-8"),
    )


def _open_parent_directory(path: Path) -> tuple[int, str]:
    if not path.is_absolute() or ".." in path.parts or path.name in {"", ".", ".."}:
        raise ApplyOperationError("Configured apply path is invalid")
    flags = os.O_RDONLY | os.O_CLOEXEC | getattr(os, "O_DIRECTORY", 0)
    nofollow = getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open("/", flags)
    try:
        for component in path.parts[1:-1]:
            next_descriptor = os.open(
                component,
                flags | nofollow,
                dir_fd=descriptor,
            )
            os.close(descriptor)
            descriptor = next_descriptor
        return descriptor, path.name
    except OSError as exc:
        os.close(descriptor)
        raise ApplyOperationError("Configured apply path cannot be opened safely") from exc


def _read_file(path: Path, maximum_bytes: int = MAX_ARTIFACT_BYTES) -> FileSnapshot:
    parent_fd, name = _open_parent_directory(path)
    file_fd = -1
    try:
        try:
            file_fd = os.open(
                name,
                os.O_RDONLY | os.O_CLOEXEC | getattr(os, "O_NOFOLLOW", 0),
                dir_fd=parent_fd,
            )
        except FileNotFoundError:
            return FileSnapshot(False, b"", 0, 0, 0)
        metadata = os.fstat(file_fd)
        if not stat.S_ISREG(metadata.st_mode):
            raise ApplyOperationError("Configuration artifact is not a regular file")
        if metadata.st_size > maximum_bytes:
            raise ApplyOperationError("Configuration artifact exceeds the size limit")
        with os.fdopen(file_fd, "rb", closefd=True) as handle:
            file_fd = -1
            content = handle.read(maximum_bytes + 1)
        if len(content) > maximum_bytes:
            raise ApplyOperationError("Configuration artifact exceeds the size limit")
        return FileSnapshot(
            True,
            content,
            stat.S_IMODE(metadata.st_mode),
            metadata.st_uid,
            metadata.st_gid,
        )
    except OSError as exc:
        raise ApplyOperationError("Configuration artifact cannot be read safely") from exc
    finally:
        if file_fd >= 0:
            os.close(file_fd)
        os.close(parent_fd)


def _write_all(file_fd: int, content: bytes) -> None:
    offset = 0
    while offset < len(content):
        written = os.write(file_fd, content[offset:])
        if written <= 0:
            raise OSError("short write")
        offset += written


def _atomic_replace(path: Path, content: bytes, *, mode: int, uid: int, gid: int) -> None:
    if len(content) > MAX_ARTIFACT_BYTES:
        raise ApplyOperationError("Generated configuration exceeds the size limit")
    parent_fd, name = _open_parent_directory(path)
    temporary_name = f".{name}.{uuid.uuid4().hex}.tmp"
    temporary_fd = -1
    try:
        try:
            metadata = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
        except FileNotFoundError:
            metadata = None
        if metadata is not None and not stat.S_ISREG(metadata.st_mode):
            raise ApplyOperationError("Configuration destination is not a regular file")
        temporary_fd = os.open(
            temporary_name,
            os.O_WRONLY
            | os.O_CREAT
            | os.O_EXCL
            | os.O_CLOEXEC
            | getattr(os, "O_NOFOLLOW", 0),
            0o600,
            dir_fd=parent_fd,
        )
        _write_all(temporary_fd, content)
        os.fchmod(temporary_fd, mode)
        os.fchown(temporary_fd, uid, gid)
        os.fsync(temporary_fd)
        os.close(temporary_fd)
        temporary_fd = -1
        os.rename(
            temporary_name,
            name,
            src_dir_fd=parent_fd,
            dst_dir_fd=parent_fd,
        )
        os.fsync(parent_fd)
    except ApplyOperationError:
        raise
    except OSError as exc:
        raise ApplyOperationError("Configuration artifact cannot be installed atomically") from exc
    finally:
        if temporary_fd >= 0:
            os.close(temporary_fd)
        try:
            os.unlink(temporary_name, dir_fd=parent_fd)
        except OSError:
            pass
        os.close(parent_fd)


def _remove_file(path: Path) -> None:
    parent_fd, name = _open_parent_directory(path)
    try:
        try:
            metadata = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
        except FileNotFoundError:
            return
        if not stat.S_ISREG(metadata.st_mode):
            raise ApplyOperationError("Configuration destination is not a regular file")
        os.unlink(name, dir_fd=parent_fd)
        os.fsync(parent_fd)
    except ApplyOperationError:
        raise
    except OSError as exc:
        raise ApplyOperationError("Configuration artifact cannot be removed safely") from exc
    finally:
        os.close(parent_fd)


def _loaded_identity(value: object) -> Dict[str, str]:
    if not isinstance(value, Mapping) or set(value) != {"source", "id", "revision"}:
        raise ApplyOperationError("Loaded runtime identity is invalid")
    source = value.get("source")
    identifier = value.get("id")
    revision = value.get("revision")
    if source not in {"maintained", "custom", "external"}:
        raise ApplyOperationError("Loaded runtime identity is invalid")
    if not isinstance(identifier, str) or not vehicle_configuration.IDENTIFIER_RE.fullmatch(identifier):
        raise ApplyOperationError("Loaded runtime identity is invalid")
    if not isinstance(revision, str) or not vehicle_configuration.REVISION_RE.fullmatch(revision):
        raise ApplyOperationError("Loaded runtime identity is invalid")
    return {"source": source, "id": identifier, "revision": revision}


def _loaded_core(value: Mapping[str, Any]) -> Dict[str, Any]:
    if not isinstance(value, Mapping):
        raise ApplyOperationError("Loaded runtime evidence is invalid")
    try:
        state = value["state"]
        errors = value["errors"]
        active_bus = value["active_bus"]
        interface = value["interface"]
    except KeyError as exc:
        raise ApplyOperationError("Loaded runtime evidence is invalid") from exc
    if state != "ready" or errors != []:
        raise ApplyOperationError("Loaded runtime evidence is not ready")
    if not isinstance(active_bus, str) or not vehicle_configuration.IDENTIFIER_RE.fullmatch(active_bus):
        raise ApplyOperationError("Loaded runtime bus is invalid")
    if not isinstance(interface, str) or not vehicle_configuration.INTERFACE_RE.fullmatch(interface):
        raise ApplyOperationError("Loaded runtime interface is invalid")
    return {
        "state": "ready",
        "errors": [],
        "vehicle": _loaded_identity(value.get("vehicle")),
        "bindings": _loaded_identity(value.get("bindings")),
        "active_bus": active_bus,
        "interface": interface,
    }


def _validate_snapshot_artifact(
    label: str,
    item: FileSnapshot,
    *,
    expected_uid: int,
    expected_gid: int,
) -> None:
    if not item.present:
        return
    if item.uid != expected_uid or item.gid != expected_gid:
        raise ApplyOperationError(f"Existing {label} ownership is untrusted")
    if item.mode & 0o7133:
        raise ApplyOperationError(f"Existing {label} permissions are unsafe")


def _snapshot_manifest(snapshot: ApplySnapshot) -> Dict[str, Any]:
    files: Dict[str, Any] = {}
    for label, item in snapshot.files.items():
        files[label] = {
            "present": item.present,
            "filename": f"{label}.bin" if item.present else "",
            "sha256": hashlib.sha256(item.content).hexdigest() if item.present else "",
            "mode": item.mode,
            "uid": item.uid,
            "gid": item.gid,
        }
    return {
        "schema_version": SNAPSHOT_SCHEMA_VERSION,
        "transaction_id": snapshot.transaction_id,
        "previous_loaded": dict(snapshot.previous_loaded),
        "files": files,
    }


def _trusted_rollback_root(path: Path) -> None:
    try:
        path.mkdir(parents=True, exist_ok=True, mode=0o700)
        metadata = path.lstat()
    except OSError as exc:
        raise ApplyOperationError("Rollback storage is unavailable") from exc
    if not stat.S_ISDIR(metadata.st_mode) or metadata.st_mode & 0o077:
        raise ApplyOperationError("Rollback storage is untrusted")
    if path == DEFAULT_ROLLBACK_ROOT and metadata.st_uid != 0:
        raise ApplyOperationError("Rollback storage is untrusted")


def _safe_remove_tree(path: Path, root: Path) -> None:
    if not _TRANSACTION_RE.fullmatch(path.name):
        raise ApplyOperationError("Rollback transaction path is invalid")
    try:
        root_resolved = root.resolve(strict=True)
        path_resolved = path.resolve(strict=True)
    except FileNotFoundError:
        return
    except OSError as exc:
        raise ApplyOperationError("Rollback transaction path is unavailable") from exc
    if path_resolved.parent != root_resolved:
        raise ApplyOperationError("Rollback transaction path escapes its root")
    shutil.rmtree(path_resolved)


def _validate_absolute_path(path: Path, label: str) -> None:
    text = str(path)
    if (
        not path.is_absolute()
        or ".." in path.parts
        or any(ord(character) < 32 for character in text)
    ):
        raise ApplyOperationError(f"{label} path is invalid")


def _prune_snapshots(root: Path, *, keep: set[str], limit: int = 2) -> None:
    try:
        entries = list(root.iterdir())
    except OSError as exc:
        raise ApplyOperationError("Rollback storage cannot be inspected") from exc
    candidates = []
    for entry in entries:
        if not _TRANSACTION_RE.fullmatch(entry.name) or entry.name in keep:
            continue
        try:
            metadata = entry.lstat()
        except OSError as exc:
            raise ApplyOperationError("Rollback transaction cannot be inspected") from exc
        if not stat.S_ISDIR(metadata.st_mode):
            raise ApplyOperationError("Rollback transaction is untrusted")
        candidates.append((metadata.st_mtime_ns, entry))
    candidates.sort(reverse=True, key=lambda item: item[0])
    retained = max(0, limit - len(keep))
    for _mtime, entry in candidates[retained:]:
        _safe_remove_tree(entry, root)


class RootApplyOperations:
    """Concrete operations for one root-owned vehicle configuration transaction."""

    def __init__(
        self,
        *,
        roots: vehicle_setup.CatalogueRoots,
        paths: ApplyPaths,
        service_user: str,
        service_uid: int,
        service_gid: int,
        service_home: Path,
        command_runner: Optional[CommandRunner] = None,
        wall_clock: Callable[[], float] = time.time,
        monotonic_clock: Callable[[], float] = time.monotonic,
        sleep: Callable[[float], None] = time.sleep,
        loaded_timeout: float = DEFAULT_LOADED_TIMEOUT,
        poll_interval: float = DEFAULT_POLL_INTERVAL,
        suppress_can_provisioning: bool = False,
    ):
        if not _SAFE_USER_RE.fullmatch(service_user):
            raise ApplyOperationError("Service account is invalid")
        if service_uid < 0 or service_gid < 0:
            raise ApplyOperationError("Service account metadata is invalid")
        _validate_absolute_path(service_home, "Service home")
        _validate_absolute_path(roots.maintained, "Maintained catalogue")
        _validate_absolute_path(roots.custom, "Custom catalogue")
        for label, path in (
            ("Canonical descriptor", paths.descriptor),
            ("Runtime drop-in", paths.runtime_dropin),
            ("udev rules", paths.udev_rules),
            ("Runtime status", paths.runtime_status),
            ("Rollback root", paths.rollback_root),
        ):
            _validate_absolute_path(path, label)
        self.roots = roots
        self.paths = paths
        self.service_user = service_user
        self.service_uid = service_uid
        self.service_gid = service_gid
        self.service_home = service_home
        self.command_runner = command_runner
        self.wall_clock = wall_clock
        self.monotonic_clock = monotonic_clock
        self.sleep = sleep
        self.loaded_timeout = loaded_timeout
        self.poll_interval = poll_interval
        self.suppress_can_provisioning = suppress_can_provisioning
        self._restart_started_at: Optional[float] = None

    def _run(self, argv: Sequence[str], as_user: bool = False) -> None:
        if self.command_runner is not None:
            self.command_runner(tuple(argv), as_user)
            return
        environment = {
            "PATH": "/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG": "C",
        }
        kwargs: Dict[str, Any] = {}
        if as_user:
            try:
                account = pwd.getpwuid(self.service_uid)
                groups = os.getgrouplist(account.pw_name, self.service_gid)
            except (KeyError, OSError) as exc:
                raise ApplyOperationError("Service account cannot be resolved") from exc
            if account.pw_name != self.service_user or Path(account.pw_dir) != self.service_home:
                raise ApplyOperationError("Service account metadata changed")
            environment.update(
                {
                    "HOME": str(self.service_home),
                    "USER": self.service_user,
                    "LOGNAME": self.service_user,
                    "XDG_RUNTIME_DIR": f"/run/user/{self.service_uid}",
                    "DBUS_SESSION_BUS_ADDRESS": f"unix:path=/run/user/{self.service_uid}/bus",
                }
            )
            kwargs.update(
                {
                    "user": self.service_uid,
                    "group": self.service_gid,
                    "extra_groups": groups,
                }
            )
        try:
            result = subprocess.run(
                list(argv),
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
                timeout=DEFAULT_COMMAND_TIMEOUT,
                env=environment,
                **kwargs,
            )
        except (OSError, ValueError, subprocess.TimeoutExpired) as exc:
            raise ApplyOperationError("Required system operation could not run") from exc
        if result.returncode != 0:
            raise ApplyOperationError("Required system operation failed")

    def _read_loaded_once(self) -> Mapping[str, Any]:
        loaded = vehicle_setup.read_loaded_runtime(self.paths.runtime_status)
        if not isinstance(loaded, Mapping):
            raise ApplyOperationError("Loaded runtime evidence is unavailable")
        return loaded

    def snapshot(self, transaction_id: str) -> ApplySnapshot:
        if not _TRANSACTION_RE.fullmatch(transaction_id):
            raise ApplyOperationError("Transaction identifier is invalid")
        before = _loaded_core(self._read_loaded_once())
        if before["state"] != "ready" or before["errors"]:
            raise ApplyOperationError("Current runtime cannot be used as a restoration target")
        files = {
            "descriptor": _read_file(self.paths.descriptor),
            "runtime-dropin": _read_file(self.paths.runtime_dropin),
            "udev-rules": _read_file(self.paths.udev_rules),
        }
        root_uid = 0 if os.geteuid() == 0 else os.geteuid()
        root_gid = 0 if os.geteuid() == 0 else os.getegid()
        _validate_snapshot_artifact(
            "canonical descriptor",
            files["descriptor"],
            expected_uid=root_uid,
            expected_gid=root_gid,
        )
        _validate_snapshot_artifact(
            "runtime drop-in",
            files["runtime-dropin"],
            expected_uid=self.service_uid,
            expected_gid=self.service_gid,
        )
        _validate_snapshot_artifact(
            "udev rules",
            files["udev-rules"],
            expected_uid=root_uid,
            expected_gid=root_gid,
        )
        after = _loaded_core(self._read_loaded_once())
        files_after = {
            "descriptor": _read_file(self.paths.descriptor),
            "runtime-dropin": _read_file(self.paths.runtime_dropin),
            "udev-rules": _read_file(self.paths.udev_rules),
        }
        if after != before or files_after != files:
            raise ApplyOperationError("Current configuration changed while taking the snapshot")

        _trusted_rollback_root(self.paths.rollback_root)
        _prune_snapshots(self.paths.rollback_root, keep=set(), limit=1)
        directory = self.paths.rollback_root / transaction_id
        try:
            directory.mkdir(mode=0o700)
        except FileExistsError as exc:
            raise ApplyOperationError("Rollback transaction already exists") from exc
        except OSError as exc:
            raise ApplyOperationError("Rollback transaction cannot be created") from exc

        snapshot = ApplySnapshot(transaction_id, directory, files, before)
        try:
            for label, item in files.items():
                if item.present:
                    _atomic_replace(
                        directory / f"{label}.bin",
                        item.content,
                        mode=0o600,
                        uid=os.geteuid(),
                        gid=os.getegid(),
                    )
            _atomic_replace(
                directory / "manifest.json",
                _json_bytes(_snapshot_manifest(snapshot)),
                mode=0o600,
                uid=os.geteuid(),
                gid=os.getegid(),
            )
        except Exception:
            try:
                _safe_remove_tree(directory, self.paths.rollback_root)
            except Exception:
                pass
            raise
        return snapshot

    def load_snapshot(self, transaction_id: str) -> ApplySnapshot:
        if not _TRANSACTION_RE.fullmatch(transaction_id):
            raise ApplyOperationError("Transaction identifier is invalid")
        directory = self.paths.rollback_root / transaction_id
        manifest_file = _read_file(directory / "manifest.json")
        if not manifest_file.present:
            raise ApplyOperationError("Rollback manifest is missing")
        expected_uid = 0 if os.geteuid() == 0 else os.geteuid()
        expected_gid = 0 if os.geteuid() == 0 else os.getegid()
        if (
            manifest_file.uid != expected_uid
            or manifest_file.gid != expected_gid
            or manifest_file.mode != 0o600
        ):
            raise ApplyOperationError("Rollback manifest is untrusted")
        try:
            manifest = json.loads(
                manifest_file.content.decode("utf-8"),
                object_pairs_hook=_unique_json_object,
                parse_constant=_reject_json_constant,
            )
        except (UnicodeDecodeError, json.JSONDecodeError, ApplyOperationError) as exc:
            raise ApplyOperationError("Rollback manifest is invalid") from exc
        if (
            not isinstance(manifest, dict)
            or set(manifest) != {"schema_version", "transaction_id", "previous_loaded", "files"}
            or manifest.get("schema_version") != SNAPSHOT_SCHEMA_VERSION
            or manifest.get("transaction_id") != transaction_id
            or not isinstance(manifest.get("files"), dict)
            or set(manifest["files"]) != {"descriptor", "runtime-dropin", "udev-rules"}
        ):
            raise ApplyOperationError("Rollback manifest schema is invalid")
        previous_loaded = _loaded_core(manifest.get("previous_loaded", {}))
        files: Dict[str, FileSnapshot] = {}
        for label, entry in manifest["files"].items():
            if not isinstance(entry, dict) or set(entry) != {
                "present",
                "filename",
                "sha256",
                "mode",
                "uid",
                "gid",
            }:
                raise ApplyOperationError("Rollback file manifest is invalid")
            present = entry.get("present")
            if not isinstance(present, bool):
                raise ApplyOperationError("Rollback file manifest is invalid")
            if present:
                filename = entry.get("filename")
                if filename != f"{label}.bin":
                    raise ApplyOperationError("Rollback file manifest is invalid")
                stored = _read_file(directory / filename)
                if (
                    not stored.present
                    or stored.uid != expected_uid
                    or stored.gid != expected_gid
                    or stored.mode != 0o600
                    or hashlib.sha256(stored.content).hexdigest() != entry.get("sha256")
                ):
                    raise ApplyOperationError("Rollback file checksum is invalid")
                content = stored.content
            else:
                if entry.get("filename") or entry.get("sha256"):
                    raise ApplyOperationError("Rollback file manifest is invalid")
                content = b""
            mode, uid, gid = entry.get("mode"), entry.get("uid"), entry.get("gid")
            if any(isinstance(value, bool) or not isinstance(value, int) or value < 0 for value in (mode, uid, gid)):
                raise ApplyOperationError("Rollback file metadata is invalid")
            if mode & ~0o7777:
                raise ApplyOperationError("Rollback file mode is invalid")
            files[label] = FileSnapshot(present, content, mode, uid, gid)
        return ApplySnapshot(transaction_id, directory, files, previous_loaded)

    def install(self, target: Mapping[str, Any]) -> None:
        artifacts = render_artifacts(
            target,
            self.roots,
            maintained_uid=0 if os.geteuid() == 0 else os.geteuid(),
            custom_uid=self.service_uid,
            suppress_can_provisioning=self.suppress_can_provisioning,
        )
        _atomic_replace(
            self.paths.runtime_dropin,
            artifacts.runtime_dropin,
            mode=0o644,
            uid=self.service_uid,
            gid=self.service_gid,
        )
        _atomic_replace(
            self.paths.udev_rules,
            artifacts.udev_rules,
            mode=0o644,
            uid=0 if os.geteuid() == 0 else os.geteuid(),
            gid=0 if os.geteuid() == 0 else os.getegid(),
        )
        _atomic_replace(
            self.paths.descriptor,
            artifacts.descriptor,
            mode=0o644,
            uid=0 if os.geteuid() == 0 else os.geteuid(),
            gid=0 if os.geteuid() == 0 else os.getegid(),
        )

    def reload(self, target: Mapping[str, Any]) -> None:
        vehicle_configuration.normalize_selection(target)
        self._run(("systemctl", "--user", "daemon-reload"), True)
        if self.suppress_can_provisioning:
            return
        self._run(("udevadm", "control", "--reload-rules"), False)
        self._run(("udevadm", "trigger", "--subsystem-match=net"), False)

    def restart(self) -> None:
        self._restart_started_at = self.wall_clock()
        self._run(("systemctl", "--user", "restart", "canbusd.service"), True)

    def loaded_runtime(self) -> Mapping[str, Any]:
        deadline = self.monotonic_clock() + self.loaded_timeout
        last: Optional[Mapping[str, Any]] = None
        while self.monotonic_clock() <= deadline:
            loaded = vehicle_setup.read_loaded_runtime(self.paths.runtime_status)
            if isinstance(loaded, Mapping):
                last = loaded
                updated_at = loaded.get("updated_at")
                if (
                    self._restart_started_at is None
                    or (
                        isinstance(updated_at, (int, float))
                        and not isinstance(updated_at, bool)
                        and float(updated_at) >= self._restart_started_at
                    )
                ):
                    return loaded
            self.sleep(self.poll_interval)
        if last is not None:
            raise ApplyOperationError("Loaded runtime evidence did not refresh after restart")
        raise ApplyOperationError("Loaded runtime evidence is unavailable")

    def restore(self, snapshot: object) -> None:
        if not isinstance(snapshot, ApplySnapshot):
            raise ApplyOperationError("Rollback snapshot is invalid")
        destinations = {
            "runtime-dropin": self.paths.runtime_dropin,
            "udev-rules": self.paths.udev_rules,
            "descriptor": self.paths.descriptor,
        }
        for label in ("runtime-dropin", "udev-rules", "descriptor"):
            item = snapshot.files[label]
            destination = destinations[label]
            if item.present:
                _atomic_replace(
                    destination,
                    item.content,
                    mode=item.mode,
                    uid=item.uid,
                    gid=item.gid,
                )
            else:
                _remove_file(destination)
        self._run(("systemctl", "--user", "daemon-reload"), True)
        if not self.suppress_can_provisioning:
            self._run(("udevadm", "control", "--reload-rules"), False)
            self._run(("udevadm", "trigger", "--subsystem-match=net"), False)

    def restoration_verified(
        self, snapshot: object, loaded: Mapping[str, Any]
    ) -> bool:
        if not isinstance(snapshot, ApplySnapshot):
            return False
        try:
            if _loaded_core(loaded) != dict(snapshot.previous_loaded):
                return False
            current = {
                "descriptor": _read_file(self.paths.descriptor),
                "runtime-dropin": _read_file(self.paths.runtime_dropin),
                "udev-rules": _read_file(self.paths.udev_rules),
            }
            return current == dict(snapshot.files)
        except (ApplyOperationError, OSError):
            return False

    def discard_snapshot(self, snapshot: object) -> None:
        """Remove a verified rollback snapshot after a qualification round trip."""

        if not isinstance(snapshot, ApplySnapshot):
            raise ApplyOperationError("Rollback snapshot is invalid")
        _safe_remove_tree(snapshot.directory, self.paths.rollback_root)
